services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
#    порты убрать в проде, доступ по внутренней сети docker
    ports:
      - "5432:5432"

#  раскомментировать, если хотим смотреть таблицы
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#    depends_on:
#      - db

  web:
    build: .
    env_file:
      - .env
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db