# Generated by Django 4.2 on 2023-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=2000)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
